blueprint:
  name: Fresh Air Climate Monitor
  description: >
    # Fresh Air Climate Monitor

    Intelligent room climate monitor that triggers actions when temperature/humidity is outside acceptable range. 
    Provides smart recommendations for opening or closing windows based on outdoor conditions.
    
    Supports both direct threshold values and input_number helpers for central control.

    ## Available Trigger Types

    **Basic Threshold Alerts** (when recommendation modes are disabled)
    
    Simple alerts when climate thresholds are exceeded:
    - threshold_temp_high / threshold_temp_low
    - threshold_humidity_high / threshold_humidity_low

    **Opening Recommendations** (when all openings are closed)
    
    Smart suggestions to open windows when outdoor conditions would help:
    - open_temp_high (cooling) / open_temp_low (warming)  
    - open_humidity_high (dehumidify) / open_humidity_low (humidify)

    **Closing Recommendations** (when openings are open)
    
    Smart suggestions to close windows when outdoor conditions are worse:
    - close_temp_high / close_temp_low
    - close_humidity_high / close_humidity_low

    Use `{{ trigger.id }}` in your actions to determine which scenario triggered.

    *Version:* 1.1.0
  domain: automation
  input:
    door_window_sensors:
      name: Door/Window Sensors (optional)
      description: Select one or more door/window sensors for this room. Required when opening or closing recommendations are enabled to detect opening states. Not needed for basic threshold monitoring.
      default: []
      selector:
        entity:
          multiple: true
          domain: binary_sensor
          device_class:
            - door
            - window
            - opening

    temperature_sensor:
      name: Temperature Sensor
      description: Select the temperature sensor for this room.
      selector:
        entity:
          domain: sensor
          device_class: temperature

    humidity_sensor:
      name: Humidity Sensor (optional)
      description: Select the humidity sensor for this room, if available. Only needed when humidity monitoring is enabled.
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: humidity

    enable_humidity_monitoring:
      name: Enable Humidity Monitoring
      description: Enable monitoring and recommendations for humidity.
      default: false
      selector:
        boolean: {}

    range_mode:
      name: Range Configuration Mode
      description: Choose how to define acceptable ranges.
      default: direct_values
      selector:
        select:
          options:
            - label: "Direct Values"
              value: "direct_values"
            - label: "Input Number Helpers"
              value: "input_number_helpers"

    # Direct value selectors
    temp_min_direct:
      name: Temperature Minimum (Direct)
      description: Minimum acceptable temperature (째C)
      default: 18
      selector:
        number:
          min: -10
          max: 35
          unit_of_measurement: "째C"
          step: 0.5

    temp_max_direct:
      name: Temperature Maximum (Direct)
      description: Maximum acceptable temperature (째C)
      default: 25
      selector:
        number:
          min: -10
          max: 35
          unit_of_measurement: "째C"
          step: 0.5

    humidity_min_direct:
      name: Humidity Minimum (Direct)
      description: Minimum acceptable humidity (%)
      default: 30
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          step: 1

    humidity_max_direct:
      name: Humidity Maximum (Direct)
      description: Maximum acceptable humidity (%)
      default: 60
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          step: 1

    # Input number helper selectors
    temp_min_helper:
      name: Temperature Minimum Helper (optional)
      description: Input number helper for minimum temperature. Only needed when using 'Input Number Helpers' range mode for centralized control.
      default: ""
      selector:
        entity:
          domain: input_number

    temp_max_helper:
      name: Temperature Maximum Helper (optional)
      description: Input number helper for maximum temperature. Only needed when using 'Input Number Helpers' range mode for centralized control.
      default: ""
      selector:
        entity:
          domain: input_number

    humidity_min_helper:
      name: Humidity Minimum Helper (optional)
      description: Input number helper for minimum humidity. Only needed when using 'Input Number Helpers' range mode and humidity monitoring is enabled.
      default: ""
      selector:
        entity:
          domain: input_number

    humidity_max_helper:
      name: Humidity Maximum Helper (optional)
      description: Input number helper for maximum humidity. Only needed when using 'Input Number Helpers' range mode and humidity monitoring is enabled.
      default: ""
      selector:
        entity:
          domain: input_number

    # Outdoor sensors for recommendations
    enable_opening_recommendations:
      name: Enable Opening Recommendations
      description: Suggest opening windows/doors when outdoor conditions would improve the climate inside.
      default: false
      selector:
        boolean: {}

    enable_closing_recommendations:
      name: Enable Closing Recommendations
      description: Suggest closing windows/doors when outdoor conditions are worse than indoor conditions.
      default: false
      selector:
        boolean: {}

    outdoor_temperature_sensor:
      name: Outdoor Temperature Sensor (optional)
      description: Outdoor temperature sensor for recommendations. Required when opening or closing recommendations are enabled to compare indoor vs outdoor conditions.
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: temperature

    outdoor_humidity_sensor:
      name: Outdoor Humidity Sensor (optional)
      description: Outdoor humidity sensor for recommendations. Only needed when humidity monitoring and opening/closing recommendations are both enabled.
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: humidity

    # User-defined actions
    actions:
      name: Actions (optional)
      description: Actions to run when a threshold is exceeded or a recommendation is made. Leave empty to set up monitoring without actions initially.
      default: []
      selector:
        action: {}

mode: single
max_exceeded: silent

variables:
  # Helper to check if input is a list or single entity, handle empty case
  door_window_sensors_list: >
    {% if door_window_sensors %}
      {% set s = iif(door_window_sensors is string, [door_window_sensors], door_window_sensors) %}
      {{ s }}
    {% else %}
      []
    {% endif %}

  # Get current values
  current_temperature: "{{ states(temperature_sensor) | float(0) }}"
  current_humidity: >
    {% if humidity_sensor and humidity_sensor != '' %}
      {{ states(humidity_sensor) | float(0) }}
    {% else %}
      none
    {% endif %}

  # Outdoor values
  outdoor_temperature: >
    {% if outdoor_temperature_sensor and outdoor_temperature_sensor != '' %}
      {{ states(outdoor_temperature_sensor) | float(0) }}
    {% else %}
      none
    {% endif %}
  outdoor_humidity: >
    {% if outdoor_humidity_sensor and outdoor_humidity_sensor != '' %}
      {{ states(outdoor_humidity_sensor) | float(0) }}
    {% else %}
      none
    {% endif %}

  # Range values (choose direct or helper)
  temp_min: >
    {% if range_mode == 'input_number_helpers' and temp_min_helper and temp_min_helper != '' %}
      {{ states(temp_min_helper) | float(0) }}
    {% else %}
      {{ temp_min_direct }}
    {% endif %}
  temp_max: >
    {% if range_mode == 'input_number_helpers' and temp_max_helper and temp_max_helper != '' %}
      {{ states(temp_max_helper) | float(0) }}
    {% else %}
      {{ temp_max_direct }}
    {% endif %}
  humidity_min: >
    {% if enable_humidity_monitoring %}
      {% if range_mode == 'input_number_helpers' and humidity_min_helper and humidity_min_helper != '' %}
        {{ states(humidity_min_helper) | float(0) }}
      {% else %}
        {{ humidity_min_direct }}
      {% endif %}
    {% else %}
      none
    {% endif %}
  humidity_max: >
    {% if enable_humidity_monitoring %}
      {% if range_mode == 'input_number_helpers' and humidity_max_helper and humidity_max_helper != '' %}
        {{ states(humidity_max_helper) | float(0) }}
      {% else %}
        {{ humidity_max_direct }}
      {% endif %}
    {% else %}
      none
    {% endif %}

  # Opening status (handle case where no sensors are provided)
  open_sensors_count: >
    {% if door_window_sensors_list | length > 0 %}
      {{ door_window_sensors_list | select('is_state', 'on') | list | count }}
    {% else %}
      0
    {% endif %}
  closed_sensors_count: >
    {% if door_window_sensors_list | length > 0 %}
      {{ door_window_sensors_list | select('is_state', 'off') | list | count }}
    {% else %}
      0
    {% endif %}
  all_openings_closed: >
    {% if door_window_sensors_list | length > 0 %}
      {{ closed_sensors_count == door_window_sensors_list | count }}
    {% else %}
      true
    {% endif %}
  any_openings_open: >
    {% if door_window_sensors_list | length > 0 %}
      {{ open_sensors_count > 0 }}
    {% else %}
      false
    {% endif %}

  # Differences for recommendations
  temperature_difference: >
    {% if outdoor_temperature is not none %}
      {{ outdoor_temperature - current_temperature }}
    {% else %}
      none
    {% endif %}
  humidity_difference: >
    {% if enable_humidity_monitoring and outdoor_humidity is not none and current_humidity is not none %}
      {{ outdoor_humidity - current_humidity }}
    {% else %}
      none
    {% endif %}

  # Room name
  room_name: "{{ state_attr(temperature_sensor, 'friendly_name') or temperature_sensor }}"

trigger:
  # --- Basic threshold monitoring (works regardless of recommendation settings) ---
  # Simple temperature alerts
  - platform: template
    id: threshold_temp_high
    value_template: >
      {{ current_temperature > temp_max
         and not enable_opening_recommendations
         and not enable_closing_recommendations }}

  - platform: template
    id: threshold_temp_low
    value_template: >
      {{ current_temperature < temp_min
         and not enable_opening_recommendations
         and not enable_closing_recommendations }}

  # Simple humidity alerts (if enabled)
  - platform: template
    id: threshold_humidity_high
    value_template: >
      {{ enable_humidity_monitoring
         and current_humidity is not none and humidity_max is not none
         and current_humidity > humidity_max
         and not enable_opening_recommendations
         and not enable_closing_recommendations }}

  - platform: template
    id: threshold_humidity_low
    value_template: >
      {{ enable_humidity_monitoring
         and current_humidity is not none and humidity_min is not none
         and current_humidity < humidity_min
         and not enable_opening_recommendations
         and not enable_closing_recommendations }}

  # --- Recommendations: open windows when outdoor conditions would help ---
  # Open for cooling: indoor too hot, outside cooler, all closed
  - platform: template
    id: open_temp_high
    value_template: >
      {{ enable_opening_recommendations
         and all_openings_closed
         and current_temperature > temp_max
         and outdoor_temperature is not none
         and outdoor_temperature < current_temperature - 1 }}

  # Open for warming: indoor too cold, outside warmer, all closed
  - platform: template
    id: open_temp_low
    value_template: >
      {{ enable_opening_recommendations
         and all_openings_closed
         and current_temperature < temp_min
         and outdoor_temperature is not none
         and outdoor_temperature > current_temperature + 1 }}

  # Open for dehumidifying: indoor too humid, outside drier, all closed
  - platform: template
    id: open_humidity_high
    value_template: >
      {{ enable_opening_recommendations
         and enable_humidity_monitoring
         and all_openings_closed
         and current_humidity is not none and humidity_max is not none
         and current_humidity > humidity_max
         and outdoor_humidity is not none
         and outdoor_humidity < current_humidity - 5 }}

  # Open for humidifying: indoor too dry, outside more humid, all closed
  - platform: template
    id: open_humidity_low
    value_template: >
      {{ enable_opening_recommendations
         and enable_humidity_monitoring
         and all_openings_closed
         and current_humidity is not none and humidity_min is not none
         and current_humidity < humidity_min
         and outdoor_humidity is not none
         and outdoor_humidity > current_humidity + 5 }}

  # --- Recommendations: manage climate when windows are open ---
  # Close/adjust: temperature too high despite open windows
  - platform: template
    id: close_temp_high
    value_template: >
      {{ enable_closing_recommendations
         and any_openings_open
         and current_temperature > temp_max
         and outdoor_temperature is not none
         and outdoor_temperature > current_temperature + 1 }}

  # Close/adjust: temperature too low despite open windows
  - platform: template
    id: close_temp_low
    value_template: >
      {{ enable_closing_recommendations
         and any_openings_open
         and current_temperature < temp_min
         and outdoor_temperature is not none
         and outdoor_temperature < current_temperature - 1 }}

  # Adjust ventilation: humidity too high despite open windows
  - platform: template
    id: close_humidity_high
    value_template: >
      {{ enable_closing_recommendations
         and enable_humidity_monitoring
         and any_openings_open
         and current_humidity is not none and humidity_max is not none
         and current_humidity > humidity_max
         and outdoor_humidity is not none
         and outdoor_humidity > current_humidity + 5 }}

  # Adjust ventilation: humidity too low despite open windows
  - platform: template
    id: close_humidity_low
    value_template: >
      {{ enable_closing_recommendations
         and enable_humidity_monitoring
         and any_openings_open
         and current_humidity is not none and humidity_min is not none
         and current_humidity < humidity_min
         and outdoor_humidity is not none
         and outdoor_humidity < current_humidity - 5 }}

condition: []

action:
  - variables:
      trigger_type: "{{ trigger.id }}"
      threshold_value: >
        {% if trigger.id in ['close_temp_high', 'open_temp_high', 'threshold_temp_high'] %}
          {{ temp_max }}
        {% elif trigger.id in ['close_temp_low', 'open_temp_low', 'threshold_temp_low'] %}
          {{ temp_min }}
        {% elif trigger.id in ['close_humidity_high', 'open_humidity_high', 'threshold_humidity_high'] %}
          {{ humidity_max }}
        {% elif trigger.id in ['close_humidity_low', 'open_humidity_low', 'threshold_humidity_low'] %}
          {{ humidity_min }}
        {% else %}
          none
        {% endif %}
      current_value: >
        {% if 'temp' in trigger.id %}
          {{ current_temperature }}
        {% elif 'humidity' in trigger.id %}
          {{ current_humidity }}
        {% else %}
          none
        {% endif %}
      unit: >
        {% if 'temp' in trigger.id %}
          "째C"
        {% elif 'humidity' in trigger.id %}
          "%"
        {% else %}
          ""
        {% endif %}
      recommendation_type: >
        {% if trigger.id == 'open_temp_high' %}
          open_cooling
        {% elif trigger.id == 'open_temp_low' %}
          open_warming
        {% elif trigger.id == 'open_humidity_high' %}
          open_dehumidify
        {% elif trigger.id == 'open_humidity_low' %}
          open_humidify
        {% elif trigger.id == 'close_temp_high' %}
          close_cooling
        {% elif trigger.id == 'close_temp_low' %}
          close_warming
        {% elif trigger.id == 'close_humidity_high' %}
          close_dehumidify
        {% elif trigger.id == 'close_humidity_low' %}
          close_humidify
        {% elif trigger.id.startswith('threshold_') %}
          threshold_alert
        {% else %}
          unknown
        {% endif %}

  # Run actions when conditions are met
  - choose:
      # Basic threshold alerts (when neither recommendation mode is enabled)
      - conditions:
          - condition: template
            value_template: >
              {{ trigger_type.startswith('threshold_') }}
        sequence: !input actions

      # Opening recommendations
      - conditions:
          - condition: template
            value_template: >
              {{ trigger_type.startswith('open_') and all_openings_closed }}
        sequence: !input actions

      # Closing recommendations
      - conditions:
          - condition: template
            value_template: >
              {{ trigger_type.startswith('close_') and any_openings_open }}
        sequence: !input actions

# End of blueprint
